/** 프로토타입 픽스처 — 2026-08-07 장중 ka10051 실응답에서 추출(억원).
 *  판단은 실제 밀도·분포에서만 나온다. 합성값이면 '업종이 30개나 되는' 문제가 사라진다. */
export const SECTOR_FLOW_FIXTURE = {
  "KOSPI": [
    {
      "code": "001",
      "name": "종합(KOSPI)",
      "changePct": -1.22,
      "tradeQty": 179973,
      "individual": -701,
      "foreign": -3942,
      "institution": 4723,
      "securities": 4458,
      "insurance": 158,
      "trust": 388,
      "bank": -79,
      "pension": -658,
      "etcCorp": -128,
      "privateFund": 409,
      "nation": 0
    },
    {
      "code": "002",
      "name": "대형주",
      "changePct": -1.23,
      "tradeQty": 60717,
      "individual": -1785,
      "foreign": -2543,
      "institution": 4389,
      "securities": 4160,
      "insurance": 154,
      "trust": 286,
      "bank": 1,
      "pension": -515,
      "etcCorp": -106,
      "privateFund": 258,
      "nation": 0
    },
    {
      "code": "003",
      "name": "중형주",
      "changePct": -1.33,
      "tradeQty": 42122,
      "individual": 937,
      "foreign": -1118,
      "institution": 201,
      "securities": 270,
      "insurance": -5,
      "trust": 70,
      "bank": -81,
      "pension": -134,
      "etcCorp": -27,
      "privateFund": 82,
      "nation": 0
    },
    {
      "code": "004",
      "name": "소형주",
      "changePct": -0.14,
      "tradeQty": 73676,
      "individual": -32,
      "foreign": -60,
      "institution": 92,
      "securities": 14,
      "insurance": 7,
      "trust": 27,
      "bank": 0,
      "pension": 4,
      "etcCorp": -1,
      "privateFund": 40,
      "nation": 0
    },
    {
      "code": "005",
      "name": "음식료/담배",
      "changePct": 1.7,
      "tradeQty": 2363,
      "individual": -169,
      "foreign": 83,
      "institution": 87,
      "securities": 64,
      "insurance": 7,
      "trust": 36,
      "bank": 0,
      "pension": 14,
      "etcCorp": -4,
      "privateFund": -35,
      "nation": 0
    },
    {
      "code": "006",
      "name": "섬유/의류",
      "changePct": -0.46,
      "tradeQty": 1711,
      "individual": -8,
      "foreign": 7,
      "institution": 2,
      "securities": 4,
      "insurance": 1,
      "trust": 1,
      "bank": 0,
      "pension": -3,
      "etcCorp": 0,
      "privateFund": -1,
      "nation": 0
    },
    {
      "code": "007",
      "name": "종이/목재",
      "changePct": -0.01,
      "tradeQty": 505,
      "individual": -5,
      "foreign": 5,
      "institution": 0,
      "securities": 0,
      "insurance": 0,
      "trust": 0,
      "bank": 0,
      "pension": 0,
      "etcCorp": 0,
      "privateFund": 0,
      "nation": 0
    },
    {
      "code": "008",
      "name": "화학",
      "changePct": 1.16,
      "tradeQty": 31172,
      "individual": -760,
      "foreign": 80,
      "institution": 670,
      "securities": 183,
      "insurance": 24,
      "trust": 117,
      "bank": -78,
      "pension": 285,
      "etcCorp": 9,
      "privateFund": 141,
      "nation": 0
    },
    {
      "code": "009",
      "name": "제약",
      "changePct": 0.56,
      "tradeQty": 4956,
      "individual": -392,
      "foreign": 281,
      "institution": 145,
      "securities": 89,
      "insurance": 11,
      "trust": 19,
      "bank": 0,
      "pension": 25,
      "etcCorp": -36,
      "privateFund": 1,
      "nation": 0
    },
    {
      "code": "010",
      "name": "비금속",
      "changePct": -0.35,
      "tradeQty": 643,
      "individual": -6,
      "foreign": 6,
      "institution": 0,
      "securities": 1,
      "insurance": 0,
      "trust": 0,
      "bank": 0,
      "pension": -1,
      "etcCorp": 0,
      "privateFund": 0,
      "nation": 0
    },
    {
      "code": "011",
      "name": "금속",
      "changePct": -3.27,
      "tradeQty": 8731,
      "individual": 127,
      "foreign": -297,
      "institution": 164,
      "securities": 62,
      "insurance": 20,
      "trust": 92,
      "bank": 0,
      "pension": -63,
      "etcCorp": 3,
      "privateFund": 52,
      "nation": 0
    },
    {
      "code": "012",
      "name": "기계/장비",
      "changePct": -2.59,
      "tradeQty": 5394,
      "individual": 613,
      "foreign": -595,
      "institution": -9,
      "securities": 25,
      "insurance": 8,
      "trust": -3,
      "bank": 0,
      "pension": -23,
      "etcCorp": -9,
      "privateFund": -16,
      "nation": 0
    },
    {
      "code": "013",
      "name": "전기/전자",
      "changePct": -1.24,
      "tradeQty": 54400,
      "individual": -1608,
      "foreign": -1868,
      "institution": 3687,
      "securities": 3197,
      "insurance": 113,
      "trust": 279,
      "bank": 7,
      "pension": -184,
      "etcCorp": -249,
      "privateFund": 271,
      "nation": 0
    },
    {
      "code": "014",
      "name": "의료/정밀기기",
      "changePct": -2.82,
      "tradeQty": 634,
      "individual": 16,
      "foreign": -14,
      "institution": 0,
      "securities": 3,
      "insurance": 0,
      "trust": -1,
      "bank": 0,
      "pension": -1,
      "etcCorp": 0,
      "privateFund": -2,
      "nation": 0
    },
    {
      "code": "015",
      "name": "운송장비/부품",
      "changePct": -1.38,
      "tradeQty": 5139,
      "individual": 318,
      "foreign": -272,
      "institution": -179,
      "securities": -30,
      "insurance": 10,
      "trust": -65,
      "bank": 0,
      "pension": -126,
      "etcCorp": 133,
      "privateFund": 32,
      "nation": 0
    },
    {
      "code": "016",
      "name": "유통",
      "changePct": -1.68,
      "tradeQty": 8911,
      "individual": 190,
      "foreign": -35,
      "institution": -168,
      "securities": 97,
      "insurance": -20,
      "trust": -98,
      "bank": -1,
      "pension": -140,
      "etcCorp": 14,
      "privateFund": -7,
      "nation": 0
    },
    {
      "code": "017",
      "name": "전기/가스",
      "changePct": -2.03,
      "tradeQty": 784,
      "individual": 56,
      "foreign": -68,
      "institution": 7,
      "securities": -1,
      "insurance": 2,
      "trust": 1,
      "bank": 0,
      "pension": -12,
      "etcCorp": 4,
      "privateFund": 17,
      "nation": 0
    },
    {
      "code": "018",
      "name": "건설",
      "changePct": -4.55,
      "tradeQty": 12518,
      "individual": 332,
      "foreign": -344,
      "institution": 19,
      "securities": 9,
      "insurance": 1,
      "trust": 3,
      "bank": 0,
      "pension": 15,
      "etcCorp": -6,
      "privateFund": -9,
      "nation": 0
    },
    {
      "code": "019",
      "name": "운송/창고",
      "changePct": -0.58,
      "tradeQty": 10488,
      "individual": -91,
      "foreign": 54,
      "institution": 41,
      "securities": 56,
      "insurance": -4,
      "trust": -25,
      "bank": 0,
      "pension": 11,
      "etcCorp": -3,
      "privateFund": 3,
      "nation": 0
    },
    {
      "code": "020",
      "name": "통신",
      "changePct": -1.28,
      "tradeQty": 1023,
      "individual": -21,
      "foreign": -30,
      "institution": 49,
      "securities": 60,
      "insurance": 3,
      "trust": 2,
      "bank": 0,
      "pension": 4,
      "etcCorp": 1,
      "privateFund": -21,
      "nation": 0
    },
    {
      "code": "021",
      "name": "금융",
      "changePct": -1.24,
      "tradeQty": 16315,
      "individual": 133,
      "foreign": -255,
      "institution": 138,
      "securities": 610,
      "insurance": -22,
      "trust": -108,
      "bank": -6,
      "pension": -409,
      "etcCorp": -25,
      "privateFund": 33,
      "nation": 0
    },
    {
      "code": "024",
      "name": "증권",
      "changePct": -3.41,
      "tradeQty": 5199,
      "individual": 310,
      "foreign": -167,
      "institution": -142,
      "securities": 45,
      "insurance": -4,
      "trust": -46,
      "bank": 0,
      "pension": -125,
      "etcCorp": 0,
      "privateFund": -13,
      "nation": 0
    },
    {
      "code": "025",
      "name": "보험",
      "changePct": -2.5,
      "tradeQty": 1872,
      "individual": 63,
      "foreign": -112,
      "institution": 55,
      "securities": 66,
      "insurance": 3,
      "trust": -16,
      "bank": 0,
      "pension": -19,
      "etcCorp": -5,
      "privateFund": 21,
      "nation": 0
    },
    {
      "code": "026",
      "name": "일반서비스",
      "changePct": -1.66,
      "tradeQty": 2205,
      "individual": 11,
      "foreign": -99,
      "institution": 84,
      "securities": 60,
      "insurance": 0,
      "trust": 5,
      "bank": 0,
      "pension": 23,
      "etcCorp": 3,
      "privateFund": -4,
      "nation": 0
    },
    {
      "code": "027",
      "name": "제조",
      "changePct": -1.13,
      "tradeQty": 116350,
      "individual": -1919,
      "foreign": -2601,
      "institution": 4669,
      "securities": 3606,
      "insurance": 198,
      "trust": 471,
      "bank": -71,
      "pension": 18,
      "etcCorp": -183,
      "privateFund": 443,
      "nation": 0
    },
    {
      "code": "028",
      "name": "부동산",
      "changePct": 0.82,
      "tradeQty": 4206,
      "individual": -33,
      "foreign": 13,
      "institution": 26,
      "securities": 2,
      "insurance": 1,
      "trust": 17,
      "bank": 0,
      "pension": 0,
      "etcCorp": -7,
      "privateFund": 6,
      "nation": 0
    },
    {
      "code": "029",
      "name": "IT 서비스",
      "changePct": -2.69,
      "tradeQty": 5615,
      "individual": 600,
      "foreign": -595,
      "institution": -49,
      "securities": -52,
      "insurance": -3,
      "trust": 119,
      "bank": 0,
      "pension": -60,
      "etcCorp": 40,
      "privateFund": -52,
      "nation": 0
    },
    {
      "code": "030",
      "name": "오락/문화",
      "changePct": -0.03,
      "tradeQty": 1103,
      "individual": -15,
      "foreign": 2,
      "institution": 10,
      "securities": 11,
      "insurance": 0,
      "trust": 0,
      "bank": 0,
      "pension": -3,
      "etcCorp": 2,
      "privateFund": 2,
      "nation": 0
    }
  ],
  "KOSDAQ": [
    {
      "code": "101",
      "name": "종합(KOSDAQ)",
      "changePct": -2.77,
      "tradeQty": 326552,
      "individual": 3483,
      "foreign": -2450,
      "institution": -1145,
      "securities": -1142,
      "insurance": 8,
      "trust": 115,
      "bank": 0,
      "pension": -136,
      "etcCorp": 105,
      "privateFund": 9,
      "nation": 0
    },
    {
      "code": "103",
      "name": "일반서비스",
      "changePct": -2.84,
      "tradeQty": 17342,
      "individual": 244,
      "foreign": -130,
      "institution": -127,
      "securities": -211,
      "insurance": 4,
      "trust": 45,
      "bank": 0,
      "pension": 38,
      "etcCorp": 13,
      "privateFund": -2,
      "nation": 0
    },
    {
      "code": "106",
      "name": "제조",
      "changePct": -3.06,
      "tradeQty": 238052,
      "individual": 2669,
      "foreign": -1860,
      "institution": -875,
      "securities": -747,
      "insurance": 3,
      "trust": 37,
      "bank": 0,
      "pension": -165,
      "etcCorp": 59,
      "privateFund": -4,
      "nation": 0
    },
    {
      "code": "107",
      "name": "건설",
      "changePct": -1.81,
      "tradeQty": 1429,
      "individual": 25,
      "foreign": -26,
      "institution": 0,
      "securities": -3,
      "insurance": 0,
      "trust": 3,
      "bank": 0,
      "pension": 0,
      "etcCorp": 0,
      "privateFund": 0,
      "nation": 0
    },
    {
      "code": "108",
      "name": "유통",
      "changePct": -2.55,
      "tradeQty": 11927,
      "individual": 82,
      "foreign": -54,
      "institution": -31,
      "securities": -26,
      "insurance": 0,
      "trust": -1,
      "bank": 0,
      "pension": -5,
      "etcCorp": 3,
      "privateFund": 1,
      "nation": 0
    },
    {
      "code": "110",
      "name": "운송/창고",
      "changePct": -0.71,
      "tradeQty": 25,
      "individual": 0,
      "foreign": 0,
      "institution": 0,
      "securities": 0,
      "insurance": 0,
      "trust": 0,
      "bank": 0,
      "pension": 0,
      "etcCorp": 0,
      "privateFund": 0,
      "nation": 0
    },
    {
      "code": "111",
      "name": "금융",
      "changePct": -1.57,
      "tradeQty": 4063,
      "individual": 304,
      "foreign": -209,
      "institution": -107,
      "securities": -102,
      "insurance": 0,
      "trust": 1,
      "bank": 0,
      "pension": -4,
      "etcCorp": 11,
      "privateFund": -1,
      "nation": 0
    },
    {
      "code": "115",
      "name": "음식료/담배",
      "changePct": 0.55,
      "tradeQty": 2886,
      "individual": -20,
      "foreign": 17,
      "institution": 6,
      "securities": 0,
      "insurance": 0,
      "trust": 5,
      "bank": 0,
      "pension": 0,
      "etcCorp": -2,
      "privateFund": 1,
      "nation": 0
    },
    {
      "code": "116",
      "name": "섬유/의류",
      "changePct": -0.65,
      "tradeQty": 1760,
      "individual": -3,
      "foreign": 3,
      "institution": 0,
      "securities": 0,
      "insurance": 0,
      "trust": 0,
      "bank": 0,
      "pension": 0,
      "etcCorp": 0,
      "privateFund": 0,
      "nation": 0
    },
    {
      "code": "117",
      "name": "종이/목재",
      "changePct": 6.49,
      "tradeQty": 826,
      "individual": 7,
      "foreign": -6,
      "institution": -1,
      "securities": -1,
      "insurance": 0,
      "trust": 0,
      "bank": 0,
      "pension": 0,
      "etcCorp": 0,
      "privateFund": 0,
      "nation": 0
    },
    {
      "code": "118",
      "name": "출판/매체복제",
      "changePct": -0.61,
      "tradeQty": 29,
      "individual": 0,
      "foreign": 0,
      "institution": 0,
      "securities": 0,
      "insurance": 0,
      "trust": 0,
      "bank": 0,
      "pension": 0,
      "etcCorp": 0,
      "privateFund": 0,
      "nation": 0
    },
    {
      "code": "119",
      "name": "화학",
      "changePct": -1.7,
      "tradeQty": 11851,
      "individual": 125,
      "foreign": -114,
      "institution": -19,
      "securities": -38,
      "insurance": -2,
      "trust": 0,
      "bank": 0,
      "pension": 4,
      "etcCorp": 8,
      "privateFund": 17,
      "nation": 0
    },
    {
      "code": "120",
      "name": "제약",
      "changePct": -2.85,
      "tradeQty": 16869,
      "individual": 163,
      "foreign": 20,
      "institution": -192,
      "securities": -230,
      "insurance": 8,
      "trust": 31,
      "bank": 0,
      "pension": -12,
      "etcCorp": 4,
      "privateFund": 11,
      "nation": 0
    },
    {
      "code": "121",
      "name": "비금속",
      "changePct": -2.51,
      "tradeQty": 2591,
      "individual": 5,
      "foreign": 10,
      "institution": -13,
      "securities": -9,
      "insurance": 0,
      "trust": 0,
      "bank": 0,
      "pension": -5,
      "etcCorp": 0,
      "privateFund": 0,
      "nation": 0
    },
    {
      "code": "122",
      "name": "금속",
      "changePct": -0.92,
      "tradeQty": 11921,
      "individual": 114,
      "foreign": -150,
      "institution": 31,
      "securities": -8,
      "insurance": 0,
      "trust": 34,
      "bank": 0,
      "pension": 1,
      "etcCorp": 5,
      "privateFund": 4,
      "nation": 0
    },
    {
      "code": "123",
      "name": "기계/장비",
      "changePct": -5.18,
      "tradeQty": 23006,
      "individual": 1011,
      "foreign": -456,
      "institution": -570,
      "securities": -272,
      "insurance": -8,
      "trust": -93,
      "bank": 0,
      "pension": -143,
      "etcCorp": 13,
      "privateFund": -53,
      "nation": 0
    },
    {
      "code": "124",
      "name": "전기/전자",
      "changePct": -2.44,
      "tradeQty": 144325,
      "individual": 1152,
      "foreign": -1077,
      "institution": -110,
      "securities": -158,
      "insurance": 3,
      "trust": 71,
      "bank": 0,
      "pension": -16,
      "etcCorp": 29,
      "privateFund": -11,
      "nation": 0
    },
    {
      "code": "125",
      "name": "의료/정밀기기",
      "changePct": -2.2,
      "tradeQty": 12806,
      "individual": 44,
      "foreign": -54,
      "institution": 8,
      "securities": -18,
      "insurance": 3,
      "trust": -12,
      "bank": 0,
      "pension": 7,
      "etcCorp": 0,
      "privateFund": 27,
      "nation": 0
    },
    {
      "code": "126",
      "name": "운송장비/부품",
      "changePct": -2.35,
      "tradeQty": 8296,
      "individual": 50,
      "foreign": -40,
      "institution": -10,
      "securities": -7,
      "insurance": -2,
      "trust": 1,
      "bank": 0,
      "pension": -1,
      "etcCorp": 0,
      "privateFund": -1,
      "nation": 0
    },
    {
      "code": "127",
      "name": "기타제조",
      "changePct": 0.02,
      "tradeQty": 888,
      "individual": 2,
      "foreign": -2,
      "institution": 0,
      "securities": 0,
      "insurance": 0,
      "trust": 0,
      "bank": 0,
      "pension": 0,
      "etcCorp": -1,
      "privateFund": 0,
      "nation": 0
    },
    {
      "code": "128",
      "name": "통신",
      "changePct": -1.3,
      "tradeQty": 186,
      "individual": 1,
      "foreign": -1,
      "institution": 0,
      "securities": 0,
      "insurance": 0,
      "trust": 0,
      "bank": 0,
      "pension": 0,
      "etcCorp": 0,
      "privateFund": 0,
      "nation": 0
    },
    {
      "code": "129",
      "name": "IT 서비스",
      "changePct": -1.55,
      "tradeQty": 48530,
      "individual": 152,
      "foreign": -176,
      "institution": 5,
      "securities": -39,
      "insurance": 0,
      "trust": 26,
      "bank": 0,
      "pension": 0,
      "etcCorp": 20,
      "privateFund": 17,
      "nation": 0
    },
    {
      "code": "138",
      "name": "KOSDAQ 100",
      "changePct": -3.62,
      "tradeQty": 26107,
      "individual": 1935,
      "foreign": -1037,
      "institution": -951,
      "securities": -996,
      "insurance": 7,
      "trust": 110,
      "bank": 0,
      "pension": -49,
      "etcCorp": 54,
      "privateFund": -23,
      "nation": 0
    },
    {
      "code": "139",
      "name": "KOSDAQ MID 300",
      "changePct": -2.32,
      "tradeQty": 58034,
      "individual": 1064,
      "foreign": -927,
      "institution": -185,
      "securities": -145,
      "insurance": 2,
      "trust": 9,
      "bank": 0,
      "pension": -87,
      "etcCorp": 39,
      "privateFund": 36,
      "nation": 0
    },
    {
      "code": "140",
      "name": "KOSDAQ SMALL",
      "changePct": -1.09,
      "tradeQty": 205338,
      "individual": 339,
      "foreign": -365,
      "institution": -7,
      "securities": 8,
      "insurance": -1,
      "trust": -5,
      "bank": 0,
      "pension": -1,
      "etcCorp": 31,
      "privateFund": -8,
      "nation": 0
    },
    {
      "code": "141",
      "name": "오락/문화",
      "changePct": -0.27,
      "tradeQty": 1299,
      "individual": -15,
      "foreign": 26,
      "institution": -11,
      "securities": -12,
      "insurance": 1,
      "trust": 3,
      "bank": 0,
      "pension": -1,
      "etcCorp": 0,
      "privateFund": -2,
      "nation": 0
    },
    {
      "code": "142",
      "name": "코스닥 우량기업",
      "changePct": -3.1,
      "tradeQty": 40483,
      "individual": 1465,
      "foreign": -830,
      "institution": -702,
      "securities": -569,
      "insurance": 4,
      "trust": -6,
      "bank": 0,
      "pension": -142,
      "etcCorp": 60,
      "privateFund": 10,
      "nation": 0
    },
    {
      "code": "143",
      "name": "코스닥 벤처기업",
      "changePct": -2.46,
      "tradeQty": 79900,
      "individual": 236,
      "foreign": -239,
      "institution": -20,
      "securities": -29,
      "insurance": 0,
      "trust": 8,
      "bank": 0,
      "pension": 6,
      "etcCorp": 21,
      "privateFund": -5,
      "nation": 0
    },
    {
      "code": "144",
      "name": "코스닥 중견기업",
      "changePct": -1.62,
      "tradeQty": 132743,
      "individual": 1058,
      "foreign": -810,
      "institution": -284,
      "securities": -300,
      "insurance": -1,
      "trust": 30,
      "bank": 0,
      "pension": -33,
      "etcCorp": 33,
      "privateFund": 19,
      "nation": 0
    },
    {
      "code": "145",
      "name": "코스닥 신성장기업",
      "changePct": -3.7,
      "tradeQty": 63269,
      "individual": 680,
      "foreign": -538,
      "institution": -128,
      "securities": -236,
      "insurance": 5,
      "trust": 81,
      "bank": 0,
      "pension": 33,
      "etcCorp": -11,
      "privateFund": -11,
      "nation": 0
    },
    {
      "code": "150",
      "name": "KOSDAQ 150",
      "changePct": -3.38,
      "tradeQty": 32178,
      "individual": 0,
      "foreign": 0,
      "institution": 0,
      "securities": 0,
      "insurance": 0,
      "trust": 0,
      "bank": 0,
      "pension": 0,
      "etcCorp": 0,
      "privateFund": 0,
      "nation": 0
    },
    {
      "code": "151",
      "name": "코스닥글로벌지수",
      "changePct": -2.66,
      "tradeQty": 9470,
      "individual": 940,
      "foreign": -550,
      "institution": -440,
      "securities": -554,
      "insurance": 9,
      "trust": 126,
      "bank": 0,
      "pension": -50,
      "etcCorp": 42,
      "privateFund": 29,
      "nation": 0
    }
  ]
} as const;
